### ISSUE TITLE
Docker container does not create database

### ISSUE THREAD

**Issue by CGBassPlayer** [pbogre/jetlog#5]
Hi! First of all, cool project!

When I pulled down the container and tried to run it, it would raise an error and never actually start.

Docker compose:
```yaml
services:
  jetlog:
    image: pbogre/jetlog
    volumes:
      - jetlog-data:/data
    restart: unless-stopped
    ports:
      - 7300:3000
volumes:
  jetlog-data:
```

Logs:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/server/main.py", line 1, in <module>
    from server.routers import flights, airports, statistics, geography
  File "/app/server/routers/flights.py", line 1, in <module>
    from server.database import database
  File "/app/server/database.py", line 89, in <module>
    database = Database(DATA_PATH)
               ^^^^^^^^^^^^^^^^^^^
  File "/app/server/database.py", line 49, in __init__
    self.connection = sqlite3.connect(db_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
Database file not found, creating it...
exited with code 1
```

**Comment by CGBassPlayer** [comment]
Seems to be a file permission issue! Use caution with docker volumes!

**Comment by unixfy** [comment]
I'm running into the same error - how did you resolve this?

**Comment by CGBassPlayer** [comment]
I ended up going with a bind mount instead of a volume and I made sure the folder I am binding to was already created is owned by my user

**Comment by pbogre** [comment]
Yes, unfortunately the user must first create the directory to be bound as volume, otherwise the container will not have permission to modify it. Otherwise, the user will have to manually `chown` the volume to the appropriate permissions. I will add this as a disclaimer in the README for now.
